// src/pages/Payments.jsx
import { Card, PageSection, SectionTitle } from '../components/ui/index.js'

export default function Payments() {
  return (
    <PageSection>
      <SectionTitle>Payments</SectionTitle>
      <Card className="grid gap-1.5" padded="md">
        <p className="text-slate-500">Scheduled Payments</p>
        <strong className="text-xl font-semibold text-slate-900">3 upcoming bills</strong>
        <span className="text-slate-500">
          Electricity, internet, and credit card due this week.
        </span>
      </Card>
    </PageSection>
  )
}

// src/views/Payments.vue
<template>
  <section class="grid gap-4">
    <h2 class="text-3xl font-bold text-slate-900">Payments</h2>
    <div
      class="grid gap-1.5 rounded-[22px] border border-slate-900/8 bg-white/90 p-6 shadow-[0_18px_44px_rgba(31,53,88,0.08)]"
    >
      <p class="text-slate-500">Scheduled Payments</p>
      <strong class="text-xl font-semibold text-slate-900">3 upcoming bills</strong>
      <span class="text-slate-500">Electricity, internet, and credit card due this week.</span>
    </div>
  </section>
</template>
